//USER TYPES
export const GET_USER = "GET_USER"
export const LOGOUT_USER = "LOGOUT_USER"
//AUTH TYPES
export const CHANGE_EMAIL_INPUT = 'CHANGE_EMAIL_INPUT'
export const CHANGE_PASSWORD_INPUT = 'CHANGE_PASSWORD_INPUT'
//ACCOUNT TYPES
export const CREATE_ACCOUNT = 'CREATE_ACCOUNT'
export const EDIT_ACCOUNT = 'EDIT_ACCOUNT'
export const GET_ACCOUNT = 'GET_ACCOUNT'
export const GET_ALL_ACCOUNTS = 'GET_ALL_ACCOUNTS'
export const GET_ACCOUNT_BY_USER = 'GET_ACCOUNT_BY_USER'
//REVIEW TYPES
export const CREATE_REVIEW = 'CREATE_REVIEW'
export const GET_ONE_REVIEW = 'GET_ONE_REVIEW'
export const GET_REVIEWS_BY_USER = 'GET_REVIEWS_BY_USER'
export const GET_ALL_REVIEWS = 'GET_ALL_REVIEWS'
export const EDIT_REVIEW = 'EDIT_REVIEW'
export const DELETE_REVIEW = 'DELETE_REVIEW'
//CATEGORY TYPES
export const CREATE_CATEGORY = 'CREATE_CATEGORY' 
export const GET_ONE_CATEGORY = 'GET_ONE_CATEGORY'
export const GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES'
//TAG TYPES
export const CREATE_TAG = 'CREATE_TAG'
export const GET_TAG = 'GET_TAG'
export const FETCH_BY_CATEGORY = 'FETCH_BY_CATEGORY'
export const GET_REVIEW_TAGS = 'GET_REVIEW_TAGS'
export const DELETE_TAG_INSTANCE = 'DELETE_TAG_INSTANCE'